### ISSUE TITLE
Maybe make Auth Optional?

### ISSUE THREAD

**Issue by jswhisperer** [naveennaidu/novuel#4]
There is a barrier to access to test or setup locally as you need to do extra OAUTH work...
Would be nice to set the defaults as no auth and perhaps sqlite vs postgres so that it's a frictionless start.

<img width="466" alt="image" src="https://github.com/user-attachments/assets/3a92be1d-770e-46dc-8b5a-2d966851a348">

**Comment by keyproco** [comment]
I think you can just inverse the auth redirect if you want to test.

**Comment by jswhisperer** [comment]
stale
